### ISSUE TITLE
Deepspeech Model Scorer Runtime Error

### ISSUE THREAD

**Issue by GridIO** [strfx/deep-neural-transcriber#1]
I was given this error `RuntimeError: ('Can not find configured default language model at: models/pretrained-v0.9.3/deepspeech-0.9.3-models.scorer', 'Please make sure that the language model (*.scorer file) is present.')` and I am a docker noob so I cant find where I can put in the scorer file 

![Screenshot_4](https://user-images.githubusercontent.com/11026687/142619084-b8731cd3-8096-4f64-8a36-6692c42fe752.png)

**Comment by strfx** [comment]
Hi @GridIO!

Thanks for creating an issue and please excuse my late reply, somehow I missed the notification :-)

Can you please share what command you run that resulted in that error?

Make sure to run `make init` after checking out the project. That step downloads some pre-trained models from Mozilla.

Let me know if that worked!

**Comment by strfx** [comment]
Closed due to inactivity.
